CREATE DATABASE IF NOT EXISTS `tododb` DEFAULT CHARACTER SET utf8 COLLATE utf8_hungarian_ci;

USE `tododb`;

CREATE TABLE IF NOT EXISTS `todos` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);